List<String> title = [
  'GoMobile: Sounds Interesting?',
  'Flutter',
  'The Magic of Kotlin Co-routines',
  'Flutter Theming & Animation',
  'OK Google, What\'s AoG?',
  'ViewModels',
  'Train your Machine\'s Nervous System',
  'Unsupervised NLP',
  'Metaphor Detection',
  'Experiments.on(context)',
  'Flutter hai toh Mamla set hai',
  'Building for \'Next\' India',
  'Building Conversations',
  'Product Strategies',
];
List<String> subhead = [
  'Freshworks\' journey to cross-platform development',
  'Do More with Less Code',
  'rescuing developers from callback hell',
  'A training on Theming & Animation',
  'An Introduction to how your Google Assistant works.',
  'ViewModel - An important architecture component',
  'Cyclical Learning Rates for training Neural Networks',
  'The simple science of unsupervised NLP',
  '',
  '',
  '',
  '',
  'To address the fundamental shift in tools and Practices while transitioning from a Visual UI to Voice-based UI.',
  '',
];
List<String> track = [
  'GoLang',
  'Flutter',
  'Android',
  'Flutter',
  'AoG Devs',
  'Android',
  'ML/AI',
  'ML/AI',
  'ML/AI',
  'Flutter',
  'Flutter',
  'Cloud',
  'AoG Devs',
  'Entrepreneurship',
];
List<String> format = [
  'session',
  'session',
  'session',
  'session',
  'session',
  'session',
  'session',
  'session',
  'session',
  'workshop',
  'session',
  'session',
  'session',
  'session',
];
List<String> featureImageURI = [
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];
List<String> speaker = [
  'Vignesh Ramachandra',
  'Pooja Bhaumik',
  'Rivu Chakraborty',
  'Dhurmil Shah',
  'Saurabh Rajpal',
  'Rimjhim Bhadhani',
  'Sayak Paul',
  'Anubhav Singh',
  'Malay Pramanik',
  'Raveesh Agarwal',
  'Pawan Kumar',
  'Prajyot Manikar',
  'Shuvam Manna',
  'Abhishek Rungta',
];
List<int> roomNumber = [
  2,
  1,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  2,
  1,
];
